POST http://localhost:9009/pipelines/schedule
Content-Type: application/json

{
  "pipeline": "create_release"
}

###

GET http://localhost:9009/pipelines

###

GET http://localhost:9009/pipelines/jobs
