pipelines:
  create_release:
    tasks:
      lint:
        script:
          - staticcheck $(go list ./... | grep -v /vendor/)
          - go vet $(go list ./... | grep -v /vendor/)
      test:
        script:
          - go test ./...
      do_something_long:
        script:
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Tick
          - sleep 1
          - echo Tock
          - sleep 1
          - echo Dong
      build:
        script:
          - go build -o bin/prunner .
        depends_on: [lint, test, do_something_long]

  test_it:
    tasks:
      lint:
        script:
          - echo "Foo"

  fail_it:
    tasks:
      lint:
        script:
          - echo "Foo"
      no-work:
        script:
          - go for a walk

  queue_it:
    concurrency: 2
    queue_limit: 3
    tasks:
      lint:
        script:
          - echo "Starting something busy"
          - sleep 3
          - echo "25% done"
          - sleep 2
          - echo "50% done"
          - sleep 4
          - echo "75% done"
          - sleep 1
          - echo "100% done"

  replace_it:
    queue_strategy: replace
    tasks:
      lint:
        script:
          - echo "Starting something busy"
          - sleep 2
          - echo "25% done"
          - sleep 3
          - echo "50% done"
          - sleep 4
          - echo "75% done"
          - sleep 2
          - echo "100% done"
